version: '3'

services:
    nginx:
        build: 
            context: .
            dockerfile: ./.devops/nginx/Dockerfile
        container_name: booky-restful-api-nginx-container
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - data:/var/www/html
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: booky-restful-api-php-fpm-container
        environment:
            DB_HOSTNAME: db
            DB_DATABASE: booky # change accordingly
            DB_USERNAME: demo
            DB_PASSWORD: demo
        volumes:
            - data:/var/www/html
    db:
        image: mysql:5.6
        container_name: booky-restful-api-db-container
        ports: 
            - "5000:3306"
        volumes:
            - ./app/database:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_DATABASE: booky
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
            MYSQL_USER: demo
            MYSQL_PASSWORD: demo
volumes:
    data:

