version: '3'

services:
    httpd:
        build: 
            context: .
            dockerfile: ./.devops/nginx/Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - data:/var/www/html/public
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - data:/var/www/html/public
    db:
        image: mysql:5.6
        ports: 
            - "5000:3306"
        environment:
            MYSQL_DATABASE: demo
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
            MYSQL_USER: demo
            MYSQL_PASSWORD: demo
volumes:
    data:

