version: '3'

services:
    httpd:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./app:/app
            - ./.devops/nginx/default.conf:/etc/nginx/conf.d/default.conf
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app